### ISSUE TITLE
windows and s2let

### ISSUE THREAD

**Issue by aysegulucar2016** [astro-informatics/s2let-archive#2]
Can I run s2let by Matlab in Windows (64 bit)? 

I loaded ssht-public, so3-public, and fftw-3.3.4-dll64.
However s2let presents errror.

Undefined function 'ssht_inverse_mex' for input arguments of type 'double'.

I did not compile the c files by gcc.

**Comment by ixkael** [comment]
Hi,
Yes S2LET should work on Win64 but the error seems to indicated that you haven't compiled the matlab (mex) wrappers

**Comment by aysegulucar2016** [comment]
Thanks for reply. I did not see a file for compiling all c file. 

Should I compile separately all c file. 

In addition which compiler can I use ? 

Sincerely

**Comment by ixkael** [comment]
Please use the instructions in the README and Makefile to compile the C code as well as the Matlab wrappers

**Comment by aysegulucar2016** [comment]
Thanks for fast reply. I will again try. Sincerely
